### ISSUE TITLE
Integrate CI into Repository

### ISSUE THREAD

**Issue by sbouchard09** [irinafakotakis/simpleCamera390#1]
### Description
**_As a developer, I would like continuous integration to be integrated into the repository._**

tasks to complete this story:
- [x] implement Travis CI into the repository with stage separation. @soenAnt 
- [x] create unit test to confirm Travis CI functionality @g82005

**Comment by g82005** [comment]
3 errors occured while setting up Travis CI. 
In order to fix these errors, components were changed to android-22 in file ".travis.yml" and file "gradle.properties" was uploaded.
Build was now passed.

**Comment by soenAnt** [comment]
Adding build stages to travis
