### ISSUE TITLE
Velocity section

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#14]
This is a sub-task for issue #9. 
_make sure the iteration is clickable link to the milestone on github_
**Only stories that have stakeholder signoff, demo steps, and tests are counted.**

Please tag your released commit using “_git tag release1_”

Total: X stories, X points over X weeks
Iteration 1 (X stories,  X points)
Iteration 2 (X stories, X points)

**Comment by irinafakotakis** [comment]
Added to the release document.
