### ISSUE TITLE
Infrastructure section

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#17]
This is a sub-task for issue #9. 
For each library, framework, tool, etc that you chose to include in the app.
Name and link
Max 1 paragraph description of why you are using this framework.
Max 1 paragraph description of  other alternatives and why they don’t work.

**Comment by BarsemianGeorgik** [comment]
Inside the Infrastructure section of the Release 1 document
Explanation has been provided to describe why the Kotlin framework is more favorable than the Java 
to develop Android type applications.
