### ISSUE TITLE
Testing and Continuous Integration section

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#19]
This is a sub-task for issue #9. 

Each story needs a tests before it is complete. If some class/methods are missing unit tests, please describe why and how you are checking their quality. Please describe any unusually aspects of your testing approach.

List the 2 most important tests that you wrote or changed with links below.

Test File path with clickable GitHub link | What is it testing (1 line description)
-- | --
  |  

Describe your continuous integration environment. Include a link to your CI.

**Comment by g82005** [comment]
This section is done.
