### ISSUE TITLE
 Architecture Recovery

### ISSUE THREAD

**Issue by sbouchard09** [irinafakotakis/simpleCamera390#2]
### Description
_**As a developer, I would like to extract the architecture from the app and have it explained using diagrams.**_

Tasks to complete:
- [x] Class Diagram of Kotlin sub-directory
- [x] Activities Package Class Diagram
- [x] Views Package Class Diagram

**Comment by Keeran10** [comment]
The architecture of the Simple-Camera app has been extracted and documented inside the architecture recovery wiki page: 
[Architecture Recovery](https://github.com/irinafakotakis/simpleCamera390/wiki/Architecture-Recovery)

**The architecture recovery wiki page will be updated as we progress along with our implementation.**
