### ISSUE TITLE
Advanced Feature No.2 Mockup

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#25]
This is a sub-task of issue #3.

**Comment by BarsemianGeorgik** [comment]
The mockup for a advanced feature of the Simple-Camera app has been demonstrated with steps
inside the feature mockups wiki page:
<a href="https://github.com/irinafakotakis/simpleCamera390/wiki/Feature-Mockups">Feature Mockups</a>

The feature mockups wiki page will be updated as we progress along with our sprints.
