### ISSUE TITLE
Docker Color Story

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#26]
_**As a user, I would like to customize the color of the docker on my app.**_

Tasks to complete this story:
- [x] 1) separate the customize color panel into **_two categories_**: _settings_ and _camera preview_.
@Keeran10 
- [x] 2) implement a **_docker color option_** inside the _camera preview_ category from 1).
@MBenchimol 
- [x] 3) implement a **_color picker component_** that opens at the click of the docker color option. 
@irinafakotakis 
- [x] 4) implement a **_function_** that receives the color from 3) and changes the docker to that color. 
@BarsemianGeorgik 
- [x] 5) implement **_preference saving functionality_** to keep docker color modification. 
@sbouchard09

**Comment by sbouchard09** [comment]
**Acceptance Test**

This test characterizes the desired behaviour for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Output | Status |
| ---- | -----------  | --------------- | ------ | ------ |
| 1 | User selects the settings symbol | Settings menu opens | Settings menu opens | |
| 2 | User selects and drags "App dock color" slider to desired colour | | | |
| 3 | User selects back button | Settings menu closes | Settings menu closes | |
| 4 | The dock at the bottom of the screen should be the selected colour | Docker is the desired colour | Docker is the desired colour | pass |
| 5 | User closes the application | Simple Camera is closed | Simple Camera is closed | |
| 6 | User reopens the application | Simple Camera is launched | Simple Camera is launched | |
| 7 | The dock colour should be the same as the colour previously chosen by the user | Dock is the same colour | Dock is the same colour | pass |
