### ISSUE TITLE
Docker Color Option implementation

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#28]
This is a sub-task of issue #26.

The following must be implemented:
![image](https://user-images.githubusercontent.com/19395031/51958006-fda9ee80-241b-11e9-90cd-04b784712b43.png)
**_Wiki/Mockups/Basic Feature/Step3_**

**Test Case**
The implementation of the docker color option must capture user request and send a message to the color picker component.

**Comment by MBenchimol** [comment]
Delegation of "send a message to the color picker component" sub task to @irinafakotakis as she will create the class for the functionality of the component.

**Comment by MBenchimol** [comment]
Issue closed with PR #34
