### ISSUE TITLE
Mockups for Features

### ISSUE THREAD

**Issue by sbouchard09** [irinafakotakis/simpleCamera390#3]
### Description
**_As a developer, I would like mockups for features that we will be implementing._**

Tasks to complete this story:
- [x] **Mock up** of Basic Feature No.1 @BarsemianGeorgik 
- [x] **Mock up** of Advanced Feature No.1 @MBenchimol 
- [x] **Mock up** of Advanced Feature No.2 @BarsemianGeorgik

**Comment by BarsemianGeorgik** [comment]
The mockup for a basic feature of the Simple-Camera app has been demonstrated with steps
inside the feature mockups wiki page:
<a href="https://github.com/irinafakotakis/simpleCamera390/wiki/Feature-Mockups">Feature Mockups</a>

The feature mockups wiki page will be updated as we progress along with our sprints.

**Comment by Keeran10** [comment]
The mockups of our features have been documented in the wiki page:
<a href="https://github.com/irinafakotakis/simpleCamera390/wiki/Feature-Mockups">Feature Mockups</a>

The feature mockups wiki page will be updated as we progress along with our sprints.
