### ISSUE TITLE
Preference Saving Functionality implementation

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#31]
This is a sub-task of issue #26.

~~Implement a savings mechanism that ensures the user's requested docker color is set as the default color after relaunch.~~

Functionality was implemented in issue #30; see pull request #46 

**Test Case**
Verify that the docker colour change is properly applied

**Comment by sbouchard09** [comment]
Implemented during #30; see pull request #46

**Comment by sbouchard09** [comment]
reopened to commit test case for #30
