### ISSUE TITLE
B&W filter front-end 

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#38]
This is a sub-task of issue #36.

Create the front-end layout for the B&W option,

**Comment by irinafakotakis** [comment]
The icon for the black & white filter should be refactored from a star to something that better indicates what the filter does (for example, an icon of two circles: one black and one white). This would be clearer for the user.

**Comment by Keeran10** [comment]
Icon for b&w has become a subset of the Filter Suite icon implemented in pull request #76. This task has been completed.
