### ISSUE TITLE
Shutter Notification feature story

### ISSUE THREAD

**Issue by soenAnt** [irinafakotakis/simpleCamera390#60]
**As a user, I would like to be able to get confirmation via notification when I take a picture or video**

Tasks to complete this story:

- [x] create notification back-end
- [x] create notification front-end
- [x] implement the notification to get triggered by the shutter
- [x] ensure notification works in both front and back camera
- [x] ensure notification appears on every picture taken

**Comment by soenAnt** [comment]
**Acceptance Test**

This test characterizes the desired behaviour for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Output | Status |
| ---- | -----------  | --------------- | ------ | ------ |
| 1 | User clicks the shutter button | picture is taken, notification appears on top | notification is generated | |
| 2 | User drags down from top of the screen to show notification manager  | notification manager is open | previous notification is stored | pass |
| 3 | User closes notification manager | | | |
| 4 | User clicks the selfie button | front camera is activated  | | |
| 5 | User takes x number of photos | notification is triggered for x number | notifications are triggered | pass |
| 6 | User reopens the notification manager | x number of notifications are present | | pass |

**Comment by Keeran10** [comment]
Completed with PR #78.
