### ISSUE TITLE
Selfie Flash feature story

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#79]
_**"As a user, I would like to be able to use a flash on my front-facing camera."**_

This feature is not available on camera software applications on the market. Its pretty unique.

Tasks to complete this story:
- [x] Implement front-end flash icon for front-facing camera preview.
- [x] Implement back-end functionality to enable a flash during picture capture.
- [x] Write UI and unit tests for this feature.

Mockup for this feature: [Selfie-Flash](https://imgur.com/zqiqu2c)

**Comment by Keeran10** [comment]
Completed.

**Comment by g82005** [comment]
**Acceptance Test**

This test characterizes the desired behaviour for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Output | Status |
| ---- | -----------  | --------------- | ------ | ------ |
| 1 | User clicks the selfie button | front camera is activated  | front camera is on| pass |
| 2 | User clicks the selfie flash button | front camera flash is activated  | front camera flash is triggered | pass |
| 3 | User clicks the shutter | picture is taken, white screen turned is activated | picture is taken, white screen turned on for 0.5 second | pass |
| 2 | User clicks the selfie flash button | front camera flash is off | front camera flash is deactivated  | pass |
| 3 | User clicks the shutter | picture is taken normally | picture is taken, white screen turned off | pass |
