### ISSUE TITLE
Burst-Shot feature story

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#83]
**_"As a user, I would like to be able to take burst shots from my simple camera app."_**

The following will complete this story:
- [x] burst-shot will use the shutter as its trigger. Therefore, no front-end coding required.
- [x] burst-shot back-end must allow capture() to be called n times during shutter hold listener event.
- [x] burst-shot UI + unit testing

Mockup can be found here: [Burst-Shot](https://imgur.com/AoQK76l).

**Comment by Keeran10** [comment]
Completed.

**Comment by sbouchard09** [comment]
**Acceptance Test**
This test characterizes the desired behaviour for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Actual Output | Result |
| ---- | ----------- | --------------- | ------------- | ------ |
| 1 | User opens Simple Camera Application | Simple camera opens | Simple camera opens | pass |
| 2 | User holds down on the shutter button for at least 1.5 seconds | The preview screen flashes at least once to indicate an image is captured | The preview screen flashes at least once | pass |
| 3 | User opens the photo album by selecting the Settings button and then selecting the image | The photo album is opened and multiple pictures were taken | The photo album is opened and multiple pictures were taken | pass |
| 4 | User selects selfie mode by tapping the Selfie button | Selfie mode is activated | Selfie mode is activated | pass |
| 5 | User holds down on the shutter button for at least 1.5 seconds | The preview screen flashes at least once to indicate an image is captured | The preview screen flashes at least once | pass |
| 6 | User opens the photo album by selecting the Settings button and then selecting the image | The photo album is opened and multiple selfies were taken | The photo album is opened and multiple selfies were taken | pass |

**Comment by sbouchard09** [comment]
completed with PR #111 
added acceptance test
