### ISSUE TITLE
Sticker feature story

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#86]
**_"As a user, I would like to have access to a wide-range of stickers to attach to my pictures. Examples of these stickers are a timestamp and emojis"_**

The following will complete this story:
- [x] Sticker icon that opens a container of stickers on front-end. Refer to our filter suite front-end.
- [x] Sticker back-end must map chosen sticker to captured picture.
- [x] UI and unit tests for sticker feature.

Mockup for this feature can be found on our [mockup wiki page](https://github.com/irinafakotakis/simpleCamera390/wiki/Feature-Mockups).

**Comment by BarsemianGeorgik** [comment]
**Acceptance Test**

This test characterizes the desired behaviour for this story, with the most appropriate steps to take.

| Step | Description | Expected Output | Output | Status |
| ---- | -----------  | --------------- | ------ | ------ |
| 1 | User clicks on the star icon | a slider reveals type of stickers that the user can choose from | a slider shows three choices for the user to press on| pass |
| 2 | User can clicks on smiley face icon  | a static smiley face sticker appears on the screen that can be taken with the picture and saved| a smiley face appears | pass |
| 3 | User clicks on day stamp sticker | a day stamp sticker appears the the current day on the screen for the user to take a picture with the background | the smiley face sticker disappears and the day stamp appears on the screen  | pass |
| 4 | User clicks on image capture button | the image is saved with the current sticker active on the screen and no other icons | the shutter sound is heard and the picture is captured | pass |
| 5 | User goes to the internal storage folder of the android system | image shall be found with the saved sticker| the image is found with the saved sticker inside the internal storage folder | pass |

**Comment by Keeran10** [comment]
Completed.
