### ISSUE TITLE
Release 1 Document

### ISSUE THREAD

**Issue by Keeran10** [irinafakotakis/simpleCamera390#9]
**_As a stakeholder, I would like to have a complete overview of the existing app and its progress through documentation_.** 

This can be achieved with the completion of the [Release 1 Document](https://docs.google.com/document/d/1dllki-qdckWt-fp8hvOZdQFXRcKFA9hoR2VOfNF-rEM/edit). 

**Sections**
- [x] Mobile App Summary @sbouchard09 
- [x] Velocity @irinafakotakis 
- [x] Plan Up Next Release @soenAnt 
- [x] Overall Architecture and Class Diagram @Keeran10
- [x] Infrastructure @BarsemianGeorgik 
- [x] Code @MBenchimol 
- [x] Testing and Continuous Integration @g82005

**Comment by soenAnt** [comment]
Updated the Wiki with all the issues for the upcoming release 3 and the issue we have so far for release 3

**Comment by MBenchimol** [comment]
Closing issue as all subtasks have been completed
